### ISSUE TITLE
Ask for visual.py

### ISSUE THREAD

**Issue by JackKoLing** [YueLiao/CDN#12]
Hello,

Thanks for your great work.
I run your code and get the result.json file.
Now I want to visual the image and predicted annotations to analyze the error samples.

Can you provide a visual script?
 Thank you!

**Comment by zhangaixi2008** [comment]
Hi, please use the predicted result.json and the annotation file to generate the visualization results. Since the image names between the two files are corresponding one by one, this will be quite simple. I may not have the visualization script as you expect.

**Comment by JackKoLing** [comment]
> Hi, please use the predicted result.json and the annotation file to generate the visualization results. Since the image names between the two files are corresponding one by one, this will be quite simple. I may not have the visualization script as you expect.

Thank you. I have already visual the results by learn the code by HOIW. 
Thanks, YueLiao provide the PIC_HOIW(https://github.com/YueLiao/PIC_HOIW)
