### ISSUE TITLE
Results.json file has too much prediction.

### ISSUE THREAD

**Issue by JackKoLing** [YueLiao/CDN#13]
Hi, I run the test code for HICO by hico_cdn_s.pth, which got the mAP is 31.3616%, Nice work!

At the same time, it generates a results.json file. However, I review the file and found that predict has too much.
I don't know why is this (I'm a freshman in HOI).

Can you provide your results.json  or figure out some advice.

Thank you!

(PS: I will upload my results.json file for you to check. Thanks again.)
![image](https://user-images.githubusercontent.com/30818910/143801826-702c348d-efac-48c4-89c3-0b7e276a9d16.png)

**Comment by YueLiao** [comment]
You could only visualize the HOI predictions with top-(1-3) confidence scores.

**Comment by JackKoLing** [comment]
> You could only visualize the HOI predictions with top-(1-3) confidence scores.

So, I just need to select the top3 HOI scores and visual them?

Nice, but if they're passed triplet_nms function, why also has so much prediction? And this would influence the final mAP?

**Comment by JackKoLing** [comment]
> You could only visualize the HOI predictions with top-(1-3) confidence scores.

Thank you. I got.
