### ISSUE TITLE
Code of experiment

### ISSUE THREAD

**Issue by Touger** [YueLiao/CDN#14]
Hi!

Thanks for your impressive work! I noticed that there is an experiment which use pair generated by HO-PD while interaction classifier is iCAN.  The performance gain(+9mAP) is really impressive! I really want to try it myself. Could you please release the code of this experiment?

Thanks a lot!

Touger

**Comment by zhangaixi2008** [comment]
The full process is a bit complicated. First, we run the training with the source code DRG (https://github.com/vt-vl-lab/DRG), where we use configs to re-produce the pytorch version iGAN. Then, we train the HO-PD in CDN only, and generate the human-object pairs. Next, we replace the iCAN combined h-o pairs with the HO-PD generated h-o pairs during iCAN evaluation. In this way, we can generate the result in the paper. 

Here I will provide the iCAN evaluation script using the HO-PD generated pairs in the final step. For the other steps and the used files, please carefully follow the https://github.com/vt-vl-lab/DRG to train the iCAN model, and also train the HO-PD to generate the pairs, which are used in the final evaluation script.

[test_net_HICO_app_pair.py.zip](https://github.com/YueLiao/CDN/files/7641528/test_net_HICO_app_pair.py.zip)

**Comment by Touger** [comment]
My sincere thanks!

**Comment by columbia617** [comment]
Hello, I also try to make my own dataset. What is the use of piror.pickle in vcoco and how to generate it on your own dataset?
