### ISSUE TITLE
The model providing is not the best.

### ISSUE THREAD

**Issue by Devotedyang** [YueLiao/CDN#15]
Hi~ the CDN-L(R101) model you provide show the result of 63.01(Scenario 1) and 64.45(Scenario 2), which is not same as the result 63.91 and 65.89 in paper. So could you provide the model with best performance? Thanks a lot.

**Comment by YueLiao** [comment]
Could provide the GPUs and batch size during inference?

**Comment by YueLiao** [comment]
Could you provide your test/inference script? I think some wrong args setting makes the accuracy misalignment.

**Comment by Devotedyang** [comment]
> Could you provide your test/inference script? I think some wrong args setting makes the accuracy misalignment.

I just download the model and code with no changes, and then use the following commands:
python -m torch.distributed.launch \
        --nproc_per_node=4 \
        --use_env \
        main.py \
        --pretrained pretrained/vcoco_cdn_l.pth \
        --batch_size 8 \
        --dataset_file vcoco \
        --hoi_path data/v-coco \
        --num_obj_classes 81 \
        --num_verb_classes 29 \
        --backbone resnet101 \
        --num_queries 100 \
        --dec_layers_hopd 6 \
        --dec_layers_interaction 6 \
        --eval \
        --use_nms_filter
With the commands above, it shows 63.01(Scenario 1) and 64.45(Scenario 2).

**Comment by YueLiao** [comment]
This script only provides a reference result, like mAP all: 0.6332 mAP thesis: 0.6480, which is not the final performance evaluated by the official script.  You need to follow the official evaluation to obtain s1 and s2 AP.  Otherwise, the performance is affected a little by the different batch sizes.

**Comment by Devotedyang** [comment]
> This script only provides a reference result, like mAP all: 0.6332 mAP thesis: 0.6480, which is not the final performance evaluated by the official script. You need to follow the official evaluation to obtain s1 and s2 AP. Otherwise, the performance is affected a little by the different batch sizes.

Thanks! I'm new to COCO/V-COCO, your answer is very helpful.

**Comment by YueLiao** [comment]
If any issues, feel free to re-open.
