### ISSUE TITLE
Confusion about parameter conversion

### ISSUE THREAD

**Issue by ASMIftekhar** [YueLiao/CDN#18]
Hello, 
Thanks a lot for your work. As I can see in the mentioned line, you are renaming DETR decoder layer to stage2_decoder. However, in your model  there is no stage2_decoder. Does that mean you are not initializing the decoders from DETR? 

https://github.com/YueLiao/CDN/blob/71c570296ecc7194c7abf99f5207344aa9c8dabe/convert_parameters.py#L50

**Comment by YueLiao** [comment]
Thx for your interest in our work! Thanks for your reminder, It is a missing update when we format our code. However, we find some researchers have achieved higher performance with this 'wrong setting', e.g., the cdn-s has achieved about 32 mAP. Thus, it may be better without initialization for stage_2.

**Comment by ASMIftekhar** [comment]
So I assume in your reported result in the paper you do initialize the decoder with DETR weights?

**Comment by YueLiao** [comment]
> So I assume in your reported result in the paper you do initialize the decoder with DETR weights?

Yes, you are right. You could have a look at #4. The results reported by other researchers are all higher than the paper reported.

**Comment by ASMIftekhar** [comment]
Sorry for asking again. Among two decoders I guess you initialize the interaction decoder with detr weights?

**Comment by YueLiao** [comment]
> Sorry for asking again. Among two decoders I guess you initialize the interaction decoder with detr weights?

Yes, just in our orignial experiments.

**Comment by ASMIftekhar** [comment]
Thanks a lot. Closing the issue.
