### ISSUE TITLE
some code questions

### ISSUE THREAD

**Issue by mytk2012** [YueLiao/CDN#19]
for verb_score in verb_scores: 
_#64 query corresponding to verb class_
            #verb_query = np.sum(np.sort(verb_score.numpy())[::-1][:topN])
            verb_query = torch.max(verb_score)  
_#find the highest value corresponding to every query_
            obj_scores[index] = verb_query  #total 9 verb query put to the object_score query
            index += 1
thres = np.sort(obj_scores.numpy())[::-1][topN]
        keep = obj_scores > thres
        print(keep)
        out_sub_boxes = outputs['pred_sub_boxes']
        out_obj_boxes = outputs['pred_obj_boxes']
What does **keep = obj_scores > thres** mean? And  are my annotations right?

**Comment by YueLiao** [comment]
Hi, the mentioned codes are for visualization, where we only select the human-object pairs with top-3 confidences for visualization. Your annotations are right.
