### ISSUE TITLE
corre_vcoco.npy file

### ISSUE THREAD

**Issue by yujialele** [YueLiao/CDN#21]
Thank you for your good work!  Because pycocotools-python2.7 Installation is not supported in my computer so I don't get the converted file. Please provide the corre_vcoco.npy file. Thanks!

**Comment by YueLiao** [comment]
Thx for your interest in our work! This file can be found [here](https://drive.google.com/file/d/1K0OADDqvme29nvCrSM-sO3_Re3y60F3O/view?usp=sharing).
