### ISSUE TITLE
ImportError: cannot import name '_new_empty_tensor' from 'torchvision.ops'

### ISSUE THREAD

**Issue by Dawn-LX** [YueLiao/CDN#24]
A small tip, in case the future researcher have the similar issue.

my `torchvision.__version__` is "0.12.0+cu113"
and this line https://github.com/YueLiao/CDN/blob/71c570296ecc7194c7abf99f5207344aa9c8dabe/util/misc.py#L14

should be modified as:
```
# if float(torchvision.__version__[:3]) < 0.7:
if int(torchvision.__version__.split('.')[1]) < 7:  # my torchvision.__version__ is "0.12.0+cu113"
    from torchvision.ops import _new_empty_tensor
    from torchvision.ops.misc import _output_size
```

**Comment by YueLiao** [comment]
Yes, that's right.
