### ISSUE TITLE
How to evaluate with KO mode?

### ISSUE THREAD

**Issue by JacobYuan7** [YueLiao/CDN#7]
Thanks so much for your work! Would it be possible for you to release the codes for evaluating under KO mode? I am running into trouble with that.

**Comment by YueLiao** [comment]
https://gist.github.com/YueLiao/93774b9698bd06c42aa85de35f7ff190 with this script and the official matlab eval in PPDM

**Comment by YueLiao** [comment]
If still have any questions, feel free to reopen.
