### ISSUE TITLE
Questions about the interactive score

### ISSUE THREAD

**Issue by JacobYuan7** [YueLiao/CDN#8]
Thx for your contribution to HOI. As I am reading your paper and codes, I raise a question that confuses me:
I didn't find the variable in the codebase corrsponding to the interactive score. I also failed to find the training of this score. The postprocessing seems to use only the verb score and the maximum object score. Could you tell me where you define the variable and how you use it?
https://github.com/YueLiao/CDN/blob/94ee42c29de4991d95a2ae907371ecd0ea1ee8af/models/hoi.py#L440

**Comment by YueLiao** [comment]
The interactive score affects the performance very little, within 0.1% mAP. Thus, we suggest removing it. If you would like to try it, you could simply multiply the vs with interactive score through the `--use_matching' args, and ’pred_matching_logits‘ is the interactive_score.

**Comment by YueLiao** [comment]
If still have any questions, feel free to reopen.
